# Get all notes
GET http://localhost:3001/api/persons

###
// Valid get by id
GET http://localhost:3001/api/persons/619b25910a206eb41cab610a

###
// Invalid get by id
GET http://localhost:3001/api/persons/69

###

DELETE http://localhost:3001/api/persons/619bbdaeb4bf5fa874340189

### 

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Superman",
    "number": "567-227-6961"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "John"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123-456-7891"
}